version: '3'
services:
  fastapi:
    build: 
      context: ./backend
      dockerfile: dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - ENV_VAR_NAME=VALUE
    restart: always
  
  nginx:
    image: nginx:latest
    volumes:
      - ./backend/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - fastapi
    restart: always